<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="99.255" tests="5" failures="5">
  <testsuite name="Root Suite" timestamp="2025-05-11T20:48:53" tests="0" file="cypress/e2e/features/assignment_creation.feature" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Assignment Creation" timestamp="2025-05-11T20:48:53" tests="5" time="99.227" failures="5">
    <testcase name="Assignment Creation Successfully creating an assignment with required fields" time="0.000" classname="Successfully creating an assignment with required fields">
      <failure message="Timed out retrying after 10000ms: `cy.wait()` timed out waiting `10000ms` for the 1st request to the route: `loginRequest`. No request ever occurred.

https://on.cypress.io/wait" type="CypressError"><![CDATA[CypressError: Timed out retrying after 10000ms: `cy.wait()` timed out waiting `10000ms` for the 1st request to the route: `loginRequest`. No request ever occurred.

https://on.cypress.io/wait
    at cypressErr (http://localhost:3001/__cypress/runner/cypress_runner.js:75187:18)
    at Object.errByPath (http://localhost:3001/__cypress/runner/cypress_runner.js:75242:10)
    at checkForXhr (http://localhost:3001/__cypress/runner/cypress_runner.js:134821:84)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:134844:28)
    at tryCatcher (http://localhost:3001/__cypress/runner/cypress_runner.js:1807:23)
    at Promise.attempt.Promise.try (http://localhost:3001/__cypress/runner/cypress_runner.js:4315:29)
    at whenStable (http://localhost:3001/__cypress/runner/cypress_runner.js:143192:68)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:143133:14)
    at tryCatcher (http://localhost:3001/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:3001/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:3001/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:3001/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:3001/__cypress/runner/cypress_runner.js:1701:18)
    at Promise._fulfill (http://localhost:3001/__cypress/runner/cypress_runner.js:1645:18)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:5450:46)
From Your Spec Code:
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:11031:12)
    at Registry.runStepDefininition (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:9255:48)
    at Object.fn (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10156:41)
    at runStepWithLogGroup (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:9860:36)
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10153:60)]]></failure>
    </testcase>
    <testcase name="Assignment Creation Attempting to create an assignment without required fields" time="0.000" classname="Attempting to create an assignment without required fields">
      <failure message="Timed out retrying after 10000ms: `cy.wait()` timed out waiting `10000ms` for the 1st request to the route: `loginRequest`. No request ever occurred.

https://on.cypress.io/wait" type="CypressError"><![CDATA[CypressError: Timed out retrying after 10000ms: `cy.wait()` timed out waiting `10000ms` for the 1st request to the route: `loginRequest`. No request ever occurred.

https://on.cypress.io/wait
    at cypressErr (http://localhost:3001/__cypress/runner/cypress_runner.js:75187:18)
    at Object.errByPath (http://localhost:3001/__cypress/runner/cypress_runner.js:75242:10)
    at checkForXhr (http://localhost:3001/__cypress/runner/cypress_runner.js:134821:84)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:134844:28)
    at tryCatcher (http://localhost:3001/__cypress/runner/cypress_runner.js:1807:23)
    at Promise.attempt.Promise.try (http://localhost:3001/__cypress/runner/cypress_runner.js:4315:29)
    at whenStable (http://localhost:3001/__cypress/runner/cypress_runner.js:143192:68)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:143133:14)
    at tryCatcher (http://localhost:3001/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:3001/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:3001/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:3001/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:3001/__cypress/runner/cypress_runner.js:1701:18)
    at Promise._fulfill (http://localhost:3001/__cypress/runner/cypress_runner.js:1645:18)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:5450:46)
From Your Spec Code:
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:11031:12)
    at Registry.runStepDefininition (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:9255:48)
    at Object.fn (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10156:41)
    at runStepWithLogGroup (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:9860:36)
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10153:60)]]></failure>
    </testcase>
    <testcase name="Assignment Creation Creating an assignment with file attachments" time="0.000" classname="Creating an assignment with file attachments">
      <failure message="Timed out retrying after 10000ms: `cy.wait()` timed out waiting `10000ms` for the 1st request to the route: `loginRequest`. No request ever occurred.

https://on.cypress.io/wait" type="CypressError"><![CDATA[CypressError: Timed out retrying after 10000ms: `cy.wait()` timed out waiting `10000ms` for the 1st request to the route: `loginRequest`. No request ever occurred.

https://on.cypress.io/wait
    at cypressErr (http://localhost:3001/__cypress/runner/cypress_runner.js:75187:18)
    at Object.errByPath (http://localhost:3001/__cypress/runner/cypress_runner.js:75242:10)
    at checkForXhr (http://localhost:3001/__cypress/runner/cypress_runner.js:134821:84)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:134844:28)
    at tryCatcher (http://localhost:3001/__cypress/runner/cypress_runner.js:1807:23)
    at Promise.attempt.Promise.try (http://localhost:3001/__cypress/runner/cypress_runner.js:4315:29)
    at whenStable (http://localhost:3001/__cypress/runner/cypress_runner.js:143192:68)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:143133:14)
    at tryCatcher (http://localhost:3001/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:3001/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:3001/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:3001/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:3001/__cypress/runner/cypress_runner.js:1701:18)
    at Promise._fulfill (http://localhost:3001/__cypress/runner/cypress_runner.js:1645:18)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:5450:46)
From Your Spec Code:
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:11031:12)
    at Registry.runStepDefininition (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:9255:48)
    at Object.fn (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10156:41)
    at runStepWithLogGroup (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:9860:36)
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10153:60)]]></failure>
    </testcase>
    <testcase name="Assignment Creation Creating an assignment with a past due date" time="0.000" classname="Creating an assignment with a past due date">
      <failure message="Timed out retrying after 10000ms: `cy.wait()` timed out waiting `10000ms` for the 1st request to the route: `loginRequest`. No request ever occurred.

https://on.cypress.io/wait" type="CypressError"><![CDATA[CypressError: Timed out retrying after 10000ms: `cy.wait()` timed out waiting `10000ms` for the 1st request to the route: `loginRequest`. No request ever occurred.

https://on.cypress.io/wait
    at cypressErr (http://localhost:3001/__cypress/runner/cypress_runner.js:75187:18)
    at Object.errByPath (http://localhost:3001/__cypress/runner/cypress_runner.js:75242:10)
    at checkForXhr (http://localhost:3001/__cypress/runner/cypress_runner.js:134821:84)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:134844:28)
    at tryCatcher (http://localhost:3001/__cypress/runner/cypress_runner.js:1807:23)
    at Promise.attempt.Promise.try (http://localhost:3001/__cypress/runner/cypress_runner.js:4315:29)
    at whenStable (http://localhost:3001/__cypress/runner/cypress_runner.js:143192:68)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:143133:14)
    at tryCatcher (http://localhost:3001/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:3001/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:3001/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:3001/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:3001/__cypress/runner/cypress_runner.js:1701:18)
    at Promise._fulfill (http://localhost:3001/__cypress/runner/cypress_runner.js:1645:18)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:5450:46)
From Your Spec Code:
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:11031:12)
    at Registry.runStepDefininition (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:9255:48)
    at Object.fn (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10156:41)
    at runStepWithLogGroup (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:9860:36)
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10153:60)]]></failure>
    </testcase>
    <testcase name="Assignment Creation Creating an assignment with a very long description" time="0.000" classname="Creating an assignment with a very long description">
      <failure message="Timed out retrying after 10000ms: `cy.wait()` timed out waiting `10000ms` for the 1st request to the route: `loginRequest`. No request ever occurred.

https://on.cypress.io/wait" type="CypressError"><![CDATA[CypressError: Timed out retrying after 10000ms: `cy.wait()` timed out waiting `10000ms` for the 1st request to the route: `loginRequest`. No request ever occurred.

https://on.cypress.io/wait
    at cypressErr (http://localhost:3001/__cypress/runner/cypress_runner.js:75187:18)
    at Object.errByPath (http://localhost:3001/__cypress/runner/cypress_runner.js:75242:10)
    at checkForXhr (http://localhost:3001/__cypress/runner/cypress_runner.js:134821:84)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:134844:28)
    at tryCatcher (http://localhost:3001/__cypress/runner/cypress_runner.js:1807:23)
    at Promise.attempt.Promise.try (http://localhost:3001/__cypress/runner/cypress_runner.js:4315:29)
    at whenStable (http://localhost:3001/__cypress/runner/cypress_runner.js:143192:68)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:143133:14)
    at tryCatcher (http://localhost:3001/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:3001/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:3001/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:3001/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:3001/__cypress/runner/cypress_runner.js:1701:18)
    at Promise._fulfill (http://localhost:3001/__cypress/runner/cypress_runner.js:1645:18)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:5450:46)
From Your Spec Code:
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:11031:12)
    at Registry.runStepDefininition (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:9255:48)
    at Object.fn (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10156:41)
    at runStepWithLogGroup (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:9860:36)
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_creation.feature:10153:60)]]></failure>
    </testcase>
  </testsuite>
</testsuites>