<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="1.447" tests="6" failures="6">
  <testsuite name="Root Suite" timestamp="2025-05-03T15:11:13" tests="0" file="cypress/e2e/features/assignment_submission.feature" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Assignment Submission" timestamp="2025-05-03T15:11:13" tests="6" time="1.412" failures="6">
    <testcase name="Assignment Submission Successfully submitting an assignment before deadline" time="0.000" classname="Successfully submitting an assignment before deadline">
      <failure message="`cy.visit()` failed trying to load:

http://localhost:8000/login

The response we received from your web server was:

  &gt; 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://localhost:8000/login

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
    at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:130296:76)
    at visitFailedByErr (http://localhost:8000/__cypress/runner/cypress_runner.js:129704:12)
    at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:130279:13)
    at tryCatcher (http://localhost:8000/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:8000/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:8000/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:8000/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:8000/__cypress/runner/cypress_runner.js:1697:18)
    at _drainQueueStep (http://localhost:8000/__cypress/runner/cypress_runner.js:2407:12)
    at _drainQueue (http://localhost:8000/__cypress/runner/cypress_runner.js:2400:9)
    at Async._drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:2416:5)
    at Async.drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:2286:14)
From Your Spec Code:
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:10721:12)
    at Registry.runStepDefininition (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:9245:48)
    at Object.fn (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:10146:41)
    at runStepWithLogGroup (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:9850:36)
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:10143:60)]]></failure>
    </testcase>
    <testcase name="Assignment Submission Saving a draft submission" time="0.000" classname="Saving a draft submission">
      <failure message="`cy.visit()` failed trying to load:

http://localhost:8000/login

The response we received from your web server was:

  &gt; 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://localhost:8000/login

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
    at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:130296:76)
    at visitFailedByErr (http://localhost:8000/__cypress/runner/cypress_runner.js:129704:12)
    at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:130279:13)
    at tryCatcher (http://localhost:8000/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:8000/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:8000/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:8000/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:8000/__cypress/runner/cypress_runner.js:1697:18)
    at _drainQueueStep (http://localhost:8000/__cypress/runner/cypress_runner.js:2407:12)
    at _drainQueue (http://localhost:8000/__cypress/runner/cypress_runner.js:2400:9)
    at Async._drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:2416:5)
    at Async.drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:2286:14)
From Your Spec Code:
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:10721:12)
    at Registry.runStepDefininition (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:9245:48)
    at Object.fn (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:10146:41)
    at runStepWithLogGroup (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:9850:36)
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:10143:60)]]></failure>
    </testcase>
    <testcase name="Assignment Submission Editing and finalizing a draft submission" time="0.000" classname="Editing and finalizing a draft submission">
      <failure message="`cy.visit()` failed trying to load:

http://localhost:8000/login

The response we received from your web server was:

  &gt; 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://localhost:8000/login

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
    at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:130296:76)
    at visitFailedByErr (http://localhost:8000/__cypress/runner/cypress_runner.js:129704:12)
    at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:130279:13)
    at tryCatcher (http://localhost:8000/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:8000/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:8000/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:8000/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:8000/__cypress/runner/cypress_runner.js:1697:18)
    at _drainQueueStep (http://localhost:8000/__cypress/runner/cypress_runner.js:2407:12)
    at _drainQueue (http://localhost:8000/__cypress/runner/cypress_runner.js:2400:9)
    at Async._drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:2416:5)
    at Async.drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:2286:14)
From Your Spec Code:
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:10721:12)
    at Registry.runStepDefininition (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:9245:48)
    at Object.fn (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:10146:41)
    at runStepWithLogGroup (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:9850:36)
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:10143:60)]]></failure>
    </testcase>
    <testcase name="Assignment Submission Attempting to submit after the deadline" time="0.000" classname="Attempting to submit after the deadline">
      <failure message="`cy.visit()` failed trying to load:

http://localhost:8000/login

The response we received from your web server was:

  &gt; 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://localhost:8000/login

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
    at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:130296:76)
    at visitFailedByErr (http://localhost:8000/__cypress/runner/cypress_runner.js:129704:12)
    at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:130279:13)
    at tryCatcher (http://localhost:8000/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:8000/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:8000/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:8000/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:8000/__cypress/runner/cypress_runner.js:1697:18)
    at _drainQueueStep (http://localhost:8000/__cypress/runner/cypress_runner.js:2407:12)
    at _drainQueue (http://localhost:8000/__cypress/runner/cypress_runner.js:2400:9)
    at Async._drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:2416:5)
    at Async.drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:2286:14)
From Your Spec Code:
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:10721:12)
    at Registry.runStepDefininition (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:9245:48)
    at Object.fn (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:10146:41)
    at runStepWithLogGroup (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:9850:36)
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:10143:60)]]></failure>
    </testcase>
    <testcase name="Assignment Submission Viewing submission history" time="0.000" classname="Viewing submission history">
      <failure message="`cy.visit()` failed trying to load:

http://localhost:8000/login

The response we received from your web server was:

  &gt; 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://localhost:8000/login

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
    at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:130296:76)
    at visitFailedByErr (http://localhost:8000/__cypress/runner/cypress_runner.js:129704:12)
    at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:130279:13)
    at tryCatcher (http://localhost:8000/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:8000/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:8000/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:8000/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:8000/__cypress/runner/cypress_runner.js:1697:18)
    at _drainQueueStep (http://localhost:8000/__cypress/runner/cypress_runner.js:2407:12)
    at _drainQueue (http://localhost:8000/__cypress/runner/cypress_runner.js:2400:9)
    at Async._drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:2416:5)
    at Async.drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:2286:14)
From Your Spec Code:
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:10721:12)
    at Registry.runStepDefininition (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:9245:48)
    at Object.fn (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:10146:41)
    at runStepWithLogGroup (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:9850:36)
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:10143:60)]]></failure>
    </testcase>
    <testcase name="Assignment Submission Submitting an assignment with large file attachments" time="0.000" classname="Submitting an assignment with large file attachments">
      <failure message="`cy.visit()` failed trying to load:

http://localhost:8000/login

The response we received from your web server was:

  &gt; 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

http://localhost:8000/login

The response we received from your web server was:

  > 404: Not Found

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`
    at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:130296:76)
    at visitFailedByErr (http://localhost:8000/__cypress/runner/cypress_runner.js:129704:12)
    at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:130279:13)
    at tryCatcher (http://localhost:8000/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:8000/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:8000/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:8000/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:8000/__cypress/runner/cypress_runner.js:1697:18)
    at _drainQueueStep (http://localhost:8000/__cypress/runner/cypress_runner.js:2407:12)
    at _drainQueue (http://localhost:8000/__cypress/runner/cypress_runner.js:2400:9)
    at Async._drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:2416:5)
    at Async.drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:2286:14)
From Your Spec Code:
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:10721:12)
    at Registry.runStepDefininition (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:9245:48)
    at Object.fn (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:10146:41)
    at runStepWithLogGroup (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:9850:36)
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_submission.feature:10143:60)]]></failure>
    </testcase>
  </testsuite>
</testsuites>