<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="41.699" tests="6" failures="6">
  <testsuite name="Root Suite" timestamp="2025-05-03T14:56:04" tests="0" file="cypress/e2e/features/assignment_viewing.feature" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Assignment Viewing" timestamp="2025-05-03T14:56:04" tests="6" time="41.655" failures="7">
    <testcase name="Assignment Viewing Viewing all assignments across enrolled schedules" time="0.000" classname="Viewing all assignments across enrolled schedules">
      <failure message="Timed out retrying after 6000ms: Expected to find element: `[data-testid=&quot;username&quot;]`, but never found it." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 6000ms: Expected to find element: `[data-testid="username"]`, but never found it.
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10722:12)
    at Registry.runStepDefininition (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9245:48)
    at Object.fn (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10146:41)
    at runStepWithLogGroup (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9850:36)
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10143:60)]]></failure>
    </testcase>
    <testcase name="Assignment Viewing Viewing assignments organized by schedule" time="0.000" classname="Viewing assignments organized by schedule">
      <failure message="Timed out retrying after 6000ms: Expected to find element: `[data-testid=&quot;username&quot;]`, but never found it." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 6000ms: Expected to find element: `[data-testid="username"]`, but never found it.
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10722:12)
    at Registry.runStepDefininition (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9245:48)
    at Object.fn (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10146:41)
    at runStepWithLogGroup (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9850:36)
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10143:60)]]></failure>
    </testcase>
    <testcase name="Assignment Viewing Sorting assignments by due date" time="0.000" classname="Sorting assignments by due date">
      <failure message="Timed out retrying after 6000ms: Expected to find element: `[data-testid=&quot;username&quot;]`, but never found it." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 6000ms: Expected to find element: `[data-testid="username"]`, but never found it.
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10722:12)
    at Registry.runStepDefininition (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9245:48)
    at Object.fn (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10146:41)
    at runStepWithLogGroup (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9850:36)
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10143:60)]]></failure>
    </testcase>
    <testcase name="Assignment Viewing Viewing assignments by completion status" time="0.000" classname="Viewing assignments by completion status">
      <failure message="Timed out retrying after 6000ms: Expected to find element: `[data-testid=&quot;username&quot;]`, but never found it." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 6000ms: Expected to find element: `[data-testid="username"]`, but never found it.
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10722:12)
    at Registry.runStepDefininition (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9245:48)
    at Object.fn (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10146:41)
    at runStepWithLogGroup (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9850:36)
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10143:60)]]></failure>
    </testcase>
    <testcase name="Assignment Viewing Viewing assignment details" time="0.000" classname="Viewing assignment details">
      <failure message="Timed out retrying after 6000ms: Expected to find element: `[data-testid=&quot;username&quot;]`, but never found it." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 6000ms: Expected to find element: `[data-testid="username"]`, but never found it.
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10722:12)
    at Registry.runStepDefininition (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9245:48)
    at Object.fn (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10146:41)
    at runStepWithLogGroup (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9850:36)
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10143:60)]]></failure>
    </testcase>
    <testcase name="Assignment Viewing Viewing assignments with approaching deadlines" time="0.000" classname="Viewing assignments with approaching deadlines">
      <failure message="Timed out retrying after 6000ms: Expected to find element: `[data-testid=&quot;username&quot;]`, but never found it." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 6000ms: Expected to find element: `[data-testid="username"]`, but never found it.
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10722:12)
    at Registry.runStepDefininition (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9245:48)
    at Object.fn (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10146:41)
    at runStepWithLogGroup (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:9850:36)
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/e2e/features/assignment_viewing.feature:10143:60)]]></failure>
    </testcase>
    <testcase name="Assignment Viewing &quot;after all&quot; hook for &quot;Viewing assignments with approaching deadlines&quot;" time="0.000" classname="&quot;after all&quot; hook for &quot;Viewing assignments with approaching deadlines&quot;">
      <failure message="`cy.task(&apos;generateReport&apos;)` failed with the following error:

The task &apos;generateReport&apos; was not handled in the setupNodeEvents method. The following tasks are registered: cypress-cucumber-preprocessor:append-messages, cypress-cucumber-preprocessor:test-step-started, cypress-cucumber-preprocessor:create-string-attachment, writeAllureResults, getPendingAllureResults, savePendingAllureResults

Fix this in your setupNodeEvents method here:
/Users/user/Documents/Ucll/2nd Semester/Software Engineering/frontend-bcs17/cypress.config.js

https://on.cypress.io/api/task

Because this error occurred during a `after all` hook we are skipping all of the remaining tests." type="CypressError"><![CDATA[CypressError: `cy.task('generateReport')` failed with the following error:

The task 'generateReport' was not handled in the setupNodeEvents method. The following tasks are registered: cypress-cucumber-preprocessor:append-messages, cypress-cucumber-preprocessor:test-step-started, cypress-cucumber-preprocessor:create-string-attachment, writeAllureResults, getPendingAllureResults, savePendingAllureResults

Fix this in your setupNodeEvents method here:
/Users/user/Documents/Ucll/2nd Semester/Software Engineering/frontend-bcs17/cypress.config.js

https://on.cypress.io/api/task

Because this error occurred during a `after all` hook we are skipping all of the remaining tests.
    at <unknown> (http://localhost:8000/__cypress/runner/cypress_runner.js:134589:72)
    at tryCatcher (http://localhost:8000/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:8000/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:8000/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:8000/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:8000/__cypress/runner/cypress_runner.js:1697:18)
    at _drainQueueStep (http://localhost:8000/__cypress/runner/cypress_runner.js:2407:12)
    at _drainQueue (http://localhost:8000/__cypress/runner/cypress_runner.js:2400:9)
    at Async._drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:2416:5)
    at Async.drainQueues (http://localhost:8000/__cypress/runner/cypress_runner.js:2286:14)
From Your Spec Code:
    at Context.eval (http://localhost:8000/__cypress/tests?p=cypress/support/e2e.js:13838:8)]]></failure>
    </testcase>
  </testsuite>
</testsuites>